name: Build Go Binaries

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build
      run: |
        mkdir -p build
        # go mod init myapp
        # go mod tidy
        GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -trimpath -buildvcs=false -o build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goos == 'windows' && '.exe' || '' }} -ldflags "-s -w" .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ matrix.goos }}-${{ matrix.goarch }}
        path: build/myapp-${{ matrix.goos }}-${{ matrix.goarch }}*
